### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/alarmdata#1]
- [x] add_references() - takes a map and multiple references + recomputes the summary statistics
   - @christopherkenny to set up the BAF input pieces
- [x] ~~`map_elec()` to map summary statistics over `tidyselect`ions of elections~~
- [x] 50states plans function for 1 CD states @tylersimko 
- [x] 50states map function for 1 CD states @tylersimko

**Comment by tylersimko** [comment]
@christopherkenny Last two are drafted in `make_state` branch [here](https://github.com/alarm-redist/alarmdata/tree/make_state). I can incorporate the other summary statistics when those are written.
