### ISSUE TITLE
`alarm_50state_plans()` caching means `stats=` argument is ignored

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/alarmdata#13]
If you run `alarm_50state_plans(stats=FALSE)` and it gets cached and then you later run `alarm_50state_plans(stats=TRUE)`  you don't get the stats. Vice versa if you run in reverse order.

Best solution probably is to cache the stats as a CSV separately (via `alarm_50state_stats`) and then join the stats at runtime to the plans when `stats=TRUE`

**Comment by christopherkenny** [comment]
@CoryMcCartan, good to close?
