### ISSUE TITLE
Issue with downloading WI map

### ISSUE THREAD

**Issue by aleszu** [alarm-redist/alarmdata#4]
Getting this error message when running alarm_50state_map("WI")

Error in CPL_geos_union(st_geometry(x), by_feature, is_coverage) :
Evaluation error: TopologyException: unable to assign free hole to a shell at 718869.25983380002 28851.5663298.

Thank all for a great project and package.

**Comment by christopherkenny** [comment]
Hi @aleszu. This package is not yet ready for general use, so apologies for the delay. Unlike the larger project, this supporting package is experimental and will be launched publicly in a few weeks once we are happy that it is stable.

In the interim, that type of error often depicts some sort of error when we read the shapefile from `sf`. If you call `library(sf)` before loading in the file with `alarm_50state_map('WI')`, it seems to work fine. 

We may be missing an `sf` requirement based on this though. We'll investigate this more thoroughly before release of this helper package.

**Comment by kuriwaki** [comment]
Verified that the code works this once `sf` is loaded in the library; see below.  So `sf` should be in `Imports` (it's currently only in `Suggests`)

@aleszu FYI. You can also downlaod directly from the dataverse:  https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SLCD3E

``` r
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.4.0, PROJ 8.1.1; sf_use_s2() is TRUE
library(alarmdata)

map_WI <- alarm_50state_map("WI")

map_WI
#> Simple feature collection with 7059 features and 53 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 374793 ymin: -148346.6 xmax: 894337 ymax: 386651.4
#> Projected CRS: NAD83(HARN) / Wisconsin Central
#> # A tibble: 7,059 × 54
#>    GEOID     state county muni  county_muni cd_2010 cd_2020 vtd     pop pop_hisp
#>    <chr>     <chr> <chr>  <chr> <chr>         <int>   <dbl> <chr> <dbl>    <dbl>
#>  1 55001000… WI    Adams… 00275 Adams Coun…       3       3 0000…   528       26
#>  2 55001000… WI    Adams… 00275 Adams Coun…       3       3 0000…   638       24
#>  3 55001000… WI    Adams… 00275 Adams Coun…       3       3 0000…   243        9
#>  4 55001000… WI    Adams… 00275 Adams Coun…       3       3 0000…   352       16
#>  5 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   913       35
#>  6 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   349       24
#>  7 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   116        6
#>  8 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   333       16
#>  9 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   615       10
#> 10 55001000… WI    Adams… <NA>  Adams Coun…       3       3 0000…   215       11
#> # … with 7,049 more rows, and 44 more variables: pop_white <dbl>,
#> #   pop_black <dbl>, pop_aian <dbl>, pop_asian <dbl>, pop_nhpi <dbl>,
#> #   pop_other <dbl>, pop_two <dbl>, vap <dbl>, vap_hisp <dbl>, vap_white <dbl>,
#> #   vap_black <dbl>, vap_aian <dbl>, vap_asian <dbl>, vap_nhpi <dbl>,
#> #   vap_other <dbl>, vap_two <dbl>, pre_16_rep_tru <dbl>, pre_16_dem_cli <dbl>,
#> #   uss_16_rep_joh <dbl>, uss_16_dem_fei <dbl>, uss_18_rep_vuk <dbl>,
#> #   uss_18_dem_bal <dbl>, gov_18_rep_wal <dbl>, gov_18_dem_eve <dbl>, …
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kuriwaki** [comment]
Done in 73ae2c8c205b99fbd1ee8ba79017a800a84748c9
