### ISSUE TITLE
alarm_50state_stats

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/alarmdata#8]
Add a function to download the summary stats csv instead of the plans object.  We currently only have the plans and map Rds and doc HTML.

Could be named something like `alarm_50state_plansummary` or similar.

**Comment by christopherkenny** [comment]
Going with the title of the issue if that works @kuriwaki

**Comment by kuriwaki** [comment]
Sure. Would be good to add it to the documentation, then this is resolved.

**Comment by christopherkenny** [comment]
Sorry always forget about that
