### ISSUE TITLE
Add cd/state leg distinction to alarm_50state_*?

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/alarmdata#9]
Currently we only have cd so that is the only option, but if we later add state leg we may want an argument in the function to distinguish that (and let it default to cd for now)

**Comment by christopherkenny** [comment]
Do we want it as an arg if it can't do anything else at the moment? Or is it better to add a new option that defaults to the current behavior if/when we have full coverage state leg?

**Comment by kuriwaki** [comment]
Either is fine -- just thought it might avoid some confusion in the future.
